### ISSUE TITLE
https://krlmlr.github.io/rprojroot doesn't exist anymore

### ISSUE THREAD

**Issue by jennybc** [r-lib/rprojroot#38]
Same as https://github.com/r-lib/here/issues/20 but for rprojroot. usethis links to the rprojroot pkgdown site, so it would be good to have a working URL

**Comment by jennybc** [comment]
@batpigandme Did you work your https magic here as well?

**Comment by batpigandme** [comment]
Yep – have to do 24hrs for https, but header will be good in https://github.com/r-lib/rprojroot/pull/40, and http://rprojroot.r-lib.org/ works now!
