### ISSUE TITLE
Re-licensing rprojroot

### ISSUE THREAD

**Issue by hadley** [r-lib/rprojroot#50]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-lib/rprojroot/graphs/contributors). @BarkleyBG, @karldw, @uribo, would you permit us to re-license rprojroot with the MIT license? If so, please comment "I agree" below.

* [x] [@BarkleyBG](https://github.com/r-lib/rprojroot/commits?author=BarkleyBG)  
* [x] [@karldw](https://github.com/r-lib/rprojroot/commits?author=karldw)  
* [x] [@uribo](https://github.com/r-lib/rprojroot/commits?author=uribo)

**Comment by karldw** [comment]
I agree

**Comment by BarkleyBG** [comment]
I agree

**Comment by uribo** [comment]
I agree
