### ISSUE TITLE
here(NA) treats NA as "NA"

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/rprojroot#66]
I would expect the output of `here::here(NA)` to be `NA`, or maybe the same as `here::here()`, but not a path ending with the characters "NA"..

**Comment by krlmlr** [comment]
This will need importing fs to replace `file.path()` by `fs::path()` .

**Comment by krlmlr** [comment]
I wonder if we should throw an error if one of the inputs is `NA`?

**Comment by krlmlr** [comment]
Interestingly, `NA` -> `"NA"` doesn't seem to be documented in `?file.path` . This could also be fixed upstream, I wouldn't hold my breath though.
