### ISSUE TITLE
Error: No root directory found in tests_i386/testthat and tests_x64/testthat

### ISSUE THREAD

**Issue by llrs** [r-lib/rprojroot#87]
Hi, I might be wrong but I'm using testthat to test a package and [this issue](https://github.com/r-lib/here/issues/49) has made me think the issue I'm facing might be due to rprojroot via `testthat::test_check` ->> `rprojroot::is_testthat` or something similar.

When I submit the package rtweet to `devtools::checks_win_oldrelease()`, it fails ([temporary link](https://win-builder.r-project.org/yQaQY6f059Rb/00check.log)) the checks because root directory is not found. This only happen with oldrelease in windows (with the current [pre-release version](https://github.com/ropensci/rtweet/)) not on CRAN or other R versions of the presubmission checks:

```
Running the tests in 'tests/testthat.R' failed.
Complete output:
  > # Use conditionally testthat
  > # if (requireNamespace("rtweet", quietly = TRUE)) {
  > library(testthat)
  > library(rtweet)
  > 
  > test_check("rtweet")
  Error: No root directory found in d:/RCompile/CRANguest/R-oldrelease/rtweet.Rcheck/tests_i386/testthat or its parent directories. Root criterion: contains a directory "tests"
  Execution halted
** running tests for arch 'x64' ... [2s] ERROR
  Running 'testthat.R' [1s]
Running the tests in 'tests/testthat.R' failed.
Complete output:
  > # Use conditionally testthat
  > # if (requireNamespace("rtweet", quietly = TRUE)) {
  > library(testthat)
  > library(rtweet)
  > 
  > test_check("rtweet")
  Error: No root directory found in d:/RCompile/CRANguest/R-oldrelease/rtweet.Rcheck/tests_x64/testthat or its parent directories. Root criterion: contains a directory "tests"
  Execution halted
```

I'm not sure why is this happening and why hasn't happened before (that I could find) or if it is worth fixing if R will soon(?) drop support for 32 bits systems. But I guess it was better to report it

**Comment by krlmlr** [comment]
Thanks. I don't have easy access to a Windows machine now, happy to review a PR.

**Comment by krlmlr** [comment]
i386 is not as relevant anymore.
